OnlineAcademy/Areas/PrivateTeacher/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineAcademy.Models;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using OnlineAcademy.Areas.PrivateTeacher.Data;

namespace OnlineAcademy.Areas.PrivateTeacher.Controllers
{
    public class VideoController : Controller
    {
        PrivateTeacherDbContext db = new PrivateTeacherDbContext();
        // GET: PrivateTeacher/Video
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult UploadVideo()
        {
            var model = db.VideoFiles.ToList();


            return View(model);
            //List<VideoFiles> videolist = new List<VideoFiles>();
            //string CS = ConfigurationManager.ConnectionStrings["PrivateTeacherConnection"].ConnectionString;
            //using (SqlConnection con = new SqlConnection(CS))
            //{
            //    SqlCommand cmd = new SqlCommand("spGetAllVideoFile", con);
            //    cmd.CommandType = CommandType.StoredProcedure;
            //    con.Open();
            //    SqlDataReader rdr = cmd.ExecuteReader();
            //    while (rdr.Read())
            //    {
            //        VideoFiles video = new VideoFiles();
            //        video.ID = Convert.ToInt32(rdr["ID"]);
            //        video.Name = rdr["Name"].ToString();
            //        video.FileSize = Convert.ToInt32(rdr["FileSize"]);
            //        video.FilePath = rdr["FilePath"].ToString();

            //        videolist.Add(video);
            //    }
            //}
            //return View(videolist);
        }
        [HttpPost]
        public ActionResult UploadVideo(HttpPostedFileBase fileupload)
        {
            if (fileupload != null)
            {
                string fileName = Path.GetFileName(fileupload.FileName);
                int fileSize = fileupload.ContentLength;
                int Size = fileSize / 1000;
                fileupload.SaveAs(Server.MapPath("~/VideoFileUpload/" + fileName));

                VideoFiles model = new VideoFiles();
                model.Name = fileName;
                model.FilePath = "~/VideoFileUpload/" + fileName;
                model.FileSize = Size;
                if (ModelState.IsValid)
                {
                    db.VideoFiles.Add(model);
                    db.SaveChanges();
                    return RedirectToAction("UploadVideo");

                }
                return View(model);
            }
            return RedirectToAction("UploadVideo");
        }
        
        public ActionResult Delete(string id)
        {
            var vid = Convert.ToInt32(id);
            VideoFiles deletevideo = db.VideoFiles.Find(vid);
            if (deletevideo != null)
            {
                string videoPath = Server.MapPath(deletevideo.FilePath.ToString());
                System.IO.File.Delete(videoPath);
                db.VideoFiles.Remove(deletevideo);
                db.SaveChanges();
                
            }
            return RedirectToAction("UploadVideo");
        }
    }
}

OnlineAcademy/Areas/PrivateTeacher/Views/Video/UploadVideo.cshtml
@model IEnumerable<OnlineAcademy.Areas.PrivateTeacher.Data.VideoFiles>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Upload Video</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="~/Content/docs/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/mvc/4.0/jquery.validate.unobtrusive.min.js"></script>

    <style type="text/css">
        .video-frame {
            width: 100%;
            height: 195px;
            border: 4px solid #dc3545;
            box-shadow: 1px 2px 3px #dc3545;
            border-radius: 3px;
        }

        .title {
            font-weight: 500;
            font-size: 14px;
            text-align: center;
            margin-bottom: 10px;
            margin-top: 10px;
            background-color: #dc3545;
            color: white;
            box-shadow: 1px 2px 4px #dc3545;
        }
    </style>
</head>
<body>
    <div class="container py-4">
        <h3 class="text-center text-uppercase">How to Dynamically Upload and Play Video File Using ASP.NET MVC5</h3>
        <div class="card">
            <div class="card-header bg-danger text-white">
                <h6 class="text-uppercase">video List</h6>
            </div>
            <div class="card-body">
                <div class="row">
                    <button style="margin-left: 27px; margin-bottom:10px;" type="button" class="btn btn-danger rounded-0" data-toggle="modal" data-target="#UploadVideo">
                        <i class="fa fa-plus-circle"></i> Add New
                    </button>
                    <div class="modal fade" id="UploadVideo">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Upload New video File</h4>
                                    <button type="button" class="close" data-dismiss="modal">×</button>
                                </div>
                                <div class="modal-body">
                                    @using (Html.BeginForm("UploadVideo", "Video", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                    {
                                    <div class="form-group">

                                        <label>Choose File:</label>
                                        <div class="input-group">
                                            <div class="video-frame">
                                                <video id="preview_video" style="width:100%; height:187px;" controls>
                                                    <source src="" type="video/mp4" />
                                                </video>
                                            </div>
                                            <div class="row" style="margin:1%">
                                                <div class="col-md-5 left">
                                                    <h6>Name:<span id="filename" style="font-size:small"></span></h6>
                                                </div>

                                                <div class="col-md-4 left">
                                                    <h6>Size:<span id="filesize" style="font-size:small"></span></h6>
                                                </div>
                                                <div class="col-md-3 left">

                                                    <h6>Type:<span id="filetype" style="font-size:small"></span></h6>
                                                </div>

                                            </div>
                                            </div>
                                        
                                            <div class="input-group mt-2">
                                                <div class="custom-file">
                                                    <input type="file" id="fileupload" name="fileupload" class="custom-file-input" />
                                                    <label class="custom-file-label"></label>
                                                </div>
                                                <div class="input-group-append">
                                                    <input type="submit" id="btnUpload" class="btn btn-secondary" value="Upload" />
                                                </div>
                                            </div>
                                        </div>
                                        }
                                    </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    @foreach (var item in Model)
                    {
                    <div class="col-sm-4 col-md-4 col-xs-12">
                        <div class="title">@item.Name</div>
                        <div class="video-frame">
                            <video style="width:100%; height:auto;" controls>
                                <source src="@Url.Content(@item.FilePath)" type="video/mp4" />
                            </video>
                        </div>
                        <div class="footer">
                            @*@Html.ActionLink("تفاصيل الإعلان", "AdvertiseDetails", "PTAssistant", new { UserId = item.Id, area = "PrivateTeacher" }, null)*@
                            @Html.ActionLink("حذف الفيديو", "Delete","Video", new { id = item.ID , area = "PrivateTeacher" }, new { @style = "margin-top:8px;margin-left:35%",@class="btn btn-outline-danger" })
                            @*<button type="submit" class="btn btn-outline-danger" style="margin-top:8px;margin-left:40%" id="@item.ID" >Remove</button>*@

                        </div>
                    </div>
                    }
                </div>
            </div>
        </div>
    </div>
    <script>
        $("#fileupload").change(function () {
            readURL(this);
        });
         function readURL(input) {
             if (input.files && input.files[0]) {
                 var file = input.files[0];
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#preview_video').attr('src', e.target.result);
                    
                    $('#filename').text(file.name);
                    $('#filetype').text(file.type);
                    $('#filesize').text(Math.round(file.size/1024/1024)+"MB");
                }

                reader.readAsDataURL(input.files[0]); // convert to base64 string
            }
        }

        
    </script>
</body>
</html>